### ISSUE TITLE
broken pages for the online version

### ISSUE THREAD

**Issue by simkimsia** [YugaByte/yugastore-java#4]
![image](https://user-images.githubusercontent.com/245021/60333850-ac068f80-99cc-11e9-99e9-07a49ceb3673.png)

for example the video games category is not displaying the catalogue

**Comment by rkarthik007** [comment]
Thanks for pointing out @simkimsia!
@ameyb - could you please take a look?

**Comment by ameyb** [comment]
Hey @simkimsia I am updating the online version of the app and will send you the new URL soon
